config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.metadata.harvester:
      branch: main
      repo: https://github.com/cessda/cessda.metadata.harvester
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.metadata.harvester git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-chestnut-earwig.sh
        container: qc.acc_foggy-denim-moth
  QC.Doc:
    repos:
      github.com/cessda/cessda.metadata.harvester find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-corn-scorpion.sh
        container: qc.doc_foggy-black-dachshund
      github.com/cessda/cessda.metadata.harvester git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-magnolia-barnacle.sh
        container: qc.doc_snoopy-cobalt-civet
      github.com/cessda/cessda.metadata.harvester markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-aqua-koala.sh
        container: qc.doc_slaphappy-coral-whippet
  QC.Lic:
    repos:
      github.com/cessda/cessda.metadata.harvester licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-brass-robin.sh
        container: qc.lic_wheezy-sapphire-raccoon
  QC.Met:
    repos:
      github.com/cessda/cessda.metadata.harvester cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.surly-vermilion-birman.sh
        container: qc.met_hilly-gamboge-paradise
  QC.Sty:
    repos:
      github.com/cessda/cessda.metadata.harvester checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-cerulean-akita.sh
        container: qc.sty_sloppy-pumpkin-wombat
      github.com/cessda/cessda.metadata.harvester jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-chartreuse-lion.sh
        container: qc.sty_paltry-puce-bobcat
      github.com/cessda/cessda.metadata.harvester rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.silly-wisteria-sparrow.sh
        container: qc.sty_gimpy-pear-spitz
  QC.Ver:
    repos:
      github.com/cessda/cessda.metadata.harvester get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-cerulean-angelfish.sh
        container: qc.ver_chewy-cinnamon-bison
timeout: 5400
