config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.metadata.harvester:
      branch: main
      repo: https://github.com/cessda/cessda.metadata.harvester
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.metadata.harvester git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-magenta-fish.sh
        container: qc.acc_lumpy-jade-tetra
  QC.Doc:
    repos:
      github.com/cessda/cessda.metadata.harvester find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-heliotrope-emu.sh
        container: qc.doc_cloudy-tomato-dachshund
      github.com/cessda/cessda.metadata.harvester git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-scarlet-husky.sh
        container: qc.doc_lumpy-sangria-spaniel
      github.com/cessda/cessda.metadata.harvester markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-grey-koala.sh
        container: qc.doc_grumpy-gold-squirrel
  QC.Lic:
    repos:
      github.com/cessda/cessda.metadata.harvester licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-alizarin-deer.sh
        container: qc.lic_cozy-taupe-turtle
  QC.Sty:
    repos:
      github.com/cessda/cessda.metadata.harvester checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-aquamarine-monster.sh
        container: qc.sty_breezy-magenta-liger
      github.com/cessda/cessda.metadata.harvester jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-denim-whippet.sh
        container: qc.sty_crappy-asparagus-axolotl
  QC.Ver:
    repos:
      github.com/cessda/cessda.metadata.harvester get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-purple-quail.sh
        container: qc.ver_cranky-teal-giraffe
timeout: 5400
