config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.metadata.harvester:
      branch: 489-improve-harvester-sqa-rating
      repo: https://github.com/cessda/cessda.metadata.harvester
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.metadata.harvester git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-yellow-otter.sh
        container: qc.acc_skimpy-wheat-salamander
  QC.Doc:
    repos:
      github.com/cessda/cessda.metadata.harvester find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-linen-ray.sh
        container: qc.doc_stinky-apricot-cow
      github.com/cessda/cessda.metadata.harvester git:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-brown-tarsier.sh
        container: qc.doc_lumpy-seashell-dugong
      github.com/cessda/cessda.metadata.harvester markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-mustard-labradoodle.sh
        container: qc.doc_bluesy-gamboge-avocet
  QC.Lic:
    repos:
      github.com/cessda/cessda.metadata.harvester licensee:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-sapphire-kudu.sh
        container: qc.lic_scummy-sepia-mongrel
  QC.Met:
    repos:
      github.com/cessda/cessda.metadata.harvester cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-firebrick-liger.sh
        container: qc.met_sleazy-black-lion
  QC.Sty:
    repos:
      github.com/cessda/cessda.metadata.harvester checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-dandelion-seahorse.sh
        container: qc.sty_smelly-cinnamon-cichlid
      github.com/cessda/cessda.metadata.harvester jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-khaki-dogfish.sh
        container: qc.sty_clammy-corn-squirt
  QC.Ver:
    repos:
      github.com/cessda/cessda.metadata.harvester get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-eggplant-eagle.sh
        container: qc.ver_sleazy-khaki-cockroach
timeout: 5400
